apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
  namespace: default
spec:
  params:
  - name: IMAGE
    description: Image reference
  - name: DOCKERFILE
    description: Path to Dockerfile
    default: Dockerfile
  - name: CONTEXT
    description: Build context
    default: .
  - name: BUILD_EXTRA_ARGS
    description: Extra build arguments
    default: ""
  workspaces:
  - name: source
    description: Source code workspace
  - name: storage
    description: Buildah storage workspace
  steps:
  - name: build
    image: quay.io/buildah/stable:latest
    script: |
      #!/bin/sh
      set -e
      echo "Build context: $(workspaces.source.path)/$(params.CONTEXT)"
      echo "Dockerfile: $(params.DOCKERFILE)"
      echo "Image: $(params.IMAGE)"
      echo "Extra args: $(params.BUILD_EXTRA_ARGS)"
      ls -la $(workspaces.source.path)
      cd $(workspaces.source.path)/$(params.CONTEXT)
      ls -la
      buildah bud --pull-always -f $(params.DOCKERFILE) -t $(params.IMAGE) .
      if [ "$(params.BUILD_EXTRA_ARGS)" = "--push" ]; then
        echo "Pushing image to registry..."
        buildah push $(params.IMAGE) || echo "Push failed (registry may not be configured - this is OK for testing)"
      fi
    securityContext:
      runAsUser: 0
      capabilities:
        add:
        - SETUID
        - SETGID
    env:
    - name: STORAGE_DRIVER
      value: vfs
    - name: BUILDAH_ISOLATION
      value: chroot
    - name: BUILDAH_FORMAT
      value: docker

