apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gradle
  namespace: default
spec:
  params:
  - name: ARGS
    description: Gradle arguments (space-separated)
    type: string
    default: "build"
  steps:
  - name: gradle-run
    image: gradle:8.5-jdk17
    script: |
      #!/bin/sh
      set -e
      cd $(workspaces.source.path)
      gradle $(params.ARGS)

